### ISSUE TITLE
ImportError on Ubuntu 20.04

### ISSUE THREAD

**Issue by elkinaguas** [Textualize/toolong#2]
Hello,

I want to report the following behavior when installing toolong.

**OS Info:**
```bash
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
```

**Problem:**
I installed toolong using the command `pip3 install toolong` and got the output:
```bash
ERROR: frogmouth 0.9.2 has requirement textual<0.44.0,>=0.43.0, but you'll have textual 0.50.0 which is incompatible.
Installing collected packages: python-dateutil, textual, toolong
  Attempting uninstall: textual
    Found existing installation: textual 0.43.2
    Uninstalling textual-0.43.2:
      Successfully uninstalled textual-0.43.2
Successfully installed python-dateutil-2.8.2 textual-0.50.0 toolong-1.0.0
```

When I use the command `tl` I get the following error:
```bash
Traceback (most recent call last):
  File "/home/wjtd8139/.local/bin/tl", line 5, in <module>
    from toolong.cli import run
  File "/home/wjtd8139/.local/lib/python3.8/site-packages/toolong/cli.py", line 4, in <module>
    from toolong.ui import UI
  File "/home/wjtd8139/.local/lib/python3.8/site-packages/toolong/ui.py", line 13, in <module>
    from toolong.log_view import LogView
  File "/home/wjtd8139/.local/lib/python3.8/site-packages/toolong/log_view.py", line 22, in <module>
    from toolong.messages import (
  File "/home/wjtd8139/.local/lib/python3.8/site-packages/toolong/messages.py", line 6, in <module>
    from toolong.log_file import LogFile
  File "/home/wjtd8139/.local/lib/python3.8/site-packages/toolong/log_file.py", line 14, in <module>
    from toolong.format_parser import FormatParser, ParseResult
  File "/home/wjtd8139/.local/lib/python3.8/site-packages/toolong/format_parser.py", line 4, in <module>
    from typing import TypeAlias
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/lib/python3.8/typing.py)
```

**Comment by willmcgugan** [comment]
You are trying to install toolong and trogon in the same environment. Try installing toolong in a virtual environment, it ideally with pipx.

**Comment by elkinaguas** [comment]
Trogon is not installed in the Ubuntu 20.04 machine that shows the error. I installed Toolong in another computer with Ubuntu 22.04 using pip3 and not using any type of virtual env and it works.
