### ISSUE TITLE
Error installing Toolong with pipx

### ISSUE THREAD

**Issue by eliweaver732** [Textualize/toolong#43]
OS: Linux Debian 11.8 armv7l
Python: 3.9.2
Pipx: 0.12.3.1

Command: pipx install toolong

Error: 
```py
Traceback (most recent call last):
  File "/usr/bin/pipx", line 11, in <module>
    load_entry_point('pipx==0.12.3.1', 'console_scripts', 'pipx')()
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 147, in run_pipx_command
    commands.install(
  File "/usr/lib/python3/dist-packages/pipx/commands.py", line 312, in install
    if venv.get_venv_metadata_for_package(package).package_version is None:
  File "/usr/lib/python3/dist-packages/pipx/Venv.py", line 65, in get_venv_metadata_for_package
    data = json.loads(
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Comment by willmcgugan** [comment]
This error appears to be originating from pipx, not Toolong. Maybe update pipx?

**Comment by eliweaver732** [comment]
After further testing it does appear to be the older outdated pipx package. (Thank you Debian)
I've installed Toolong via pip into a virtualenv and it's working great.

Great work Will!
